import Head from 'next/head'
import HomePage from '../components/home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Loop Studios Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Alata&family=Josefin+Sans:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <HomePage />
      </main>
    </div>
  )
}
